import {
    StyleSheet,
  } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
  
    Login: {
      flex: 1,
      backgroundColor: "white",
      zIndex: 0,
    },
    Login2: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      flex: 1,
      backgroundColor: "transparent",
      zIndex: 0,
    },
    logo: {
      color: "black",
      fontSize: 50,
      textAlign: "center",
      justifyContent: "center",
      marginTop: "30%",
      zIndex: 5,
    },
    inputView: {
      marginTop: "5%",
      marginBottom: "5%",
      zIndex: 5,
    },
    innerInput: {
      color: "black",
      width: "80%",
      fontSize: 20,
      marginTop: "2%",
      alignSelf: "center",
      borderBottomWidth: 2,
      borderBottomColor: "black",
      zIndex: 5,
    },
    forgot_button: {
      marginTop: "5%",
      alignSelf: "center",
      zIndex: 5,
    },
    loginBtn: {
      alignSelf: "center",
      justifyContent: "center",
      backgroundColor: "#fff",
      width: "65%",
      marginTop: "5%",
      marginBottom: "2.5%",
      zIndex: 5,
      borderRadius: 10,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.5,
      shadowRadius: 3.84,
      elevation: 5,
      zIndex: 5,
    },
    loginText: {
      color: "black",
      fontSize: 20,
      textAlign: "center",
      justifyContent: "center",
      padding: 10,
      zIndex: 5,
    },
    bloba: {
        position: "absolute",
        top: -260,
        left: -140,
        width: "100%",
        height: "100%",
        zIndex: 1,
      },
      blobb: {
        height: "100%",
        width: "100%",
        zIndex: 2,
        position: "absolute",
        top: -240,
        left: -180,
      },
      blobc: {
        height: "55%",
        width: "55%",
        zIndex: 3,
        position: "absolute",
        top: -120,
        left: -130,
      },
  });